### ISSUE TITLE
由于屏幕尺寸问题导致没有办法把控制台尺寸调整到220 x 50

### ISSUE THREAD

**Issue by caiyr** [hv0905/HacknetOS#5]
屏幕尺寸或者比例问题导致宽度不够，最高只能调到209 x 56，手动拖拽最高可以拖到210 x * 。

**Comment by hv0905** [comment]
这个问题可以通过修改系统DPI缩放设置或者减小控制台字体大小解决。
详见[README](https://github.com/hv0905/HacknetOS/blob/master/readme_cn.md#%E4%B8%8B%E8%BD%BD%E5%92%8C%E8%BF%90%E8%A1%8C)
