### ISSUE TITLE
The prompt word "PortHack"

### ISSUE THREAD

**Issue by RaccoonWhu** [hv0905/HacknetOS#6]
The game sometimes prompts you to type "PortHack", but in fact, it can only recognize "porthack". It should be considered to fix this BUG, otherwise, players will be very confused.
![image](https://github.com/hv0905/HacknetOS/assets/136063093/a6d82e17-7259-4955-a618-33a972558c9a)
![image-1](https://github.com/hv0905/HacknetOS/assets/136063093/cc96d543-ba91-41c3-9dcd-8d39daebd5ce)
![image](https://github.com/hv0905/HacknetOS/assets/136063093/5bcec035-2d62-43e5-8182-59f9e9909ad6)
It might be better if this bug can be fixed.

**Comment by RaccoonWhu** [comment]
![image](https://github.com/hv0905/HacknetOS/assets/136063093/6bdc197f-726f-481d-ac54-eeccdc4a4363)
And these outputs "Probe" in HacknetApplication.cpp file also do not match the command "nmap".

**Comment by hv0905** [comment]
> ![image](https://user-images.githubusercontent.com/136063093/246105376-6bdc197f-726f-481d-ac54-eeccdc4a4363.png) And these outputs "Probe" in HacknetApplication.cpp file also do not match the command "nmap".

The command output, like other components of the game, is intended to closely resemble the original 'Hacknet' game. Therefore, we have no plans to modify the `nmap` output to mimic the actual 'nmap' command in Linux. All the commands in the game have been optimized to facilitate easier understanding for computer beginners.

**Comment by hv0905** [comment]
fixed in #7
